name: Update AI News

on:
  schedule:
    - cron: '0 9 * * *'     # 每天上午9点
    - cron: '0 18 * * *'    # 每天晚上18点
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run update script
        run: python scripts/fetch_news.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@users.noreply.github.com'
          git add public/data/*.json
          git commit -m "Auto-update AI news data"
          git push
