name: Update AI News

on:
  schedule:
    - cron: '0 1 * * *'   # Run at 09:00 CST
    - cron: '0 10 * * *'  # Run at 18:00 CST

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run update script
        run: python scripts/update_news.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add public/data/news.json
          git commit -m "Auto-update AI news data" || echo "No changes to commit"
          git pull --rebase
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
